### PR TITLE
WIP: Add a Code of Conduct document

### PR DESCRIPTION
**Pull request by RadicalZephyr**
This isn't ready yet, because we still need to chat about what enforcement looks like and other such things.  But I figured this was a good thing to get out there and started on.

### CODE REVIEW

**Comment by reillysiemens** [comment]
This is vague in some places (especially enforcement I think), but I really like the idea of this and what is there now looks good to me! Obviously we don't own [barn.bike](https://barn.bike) though (yet). :stuck_out_tongue_closed_eyes:

**Comment by RadicalZephyr** [comment]
Yeah.  Did you read the http://contributor-covenant.org/ page?  Enforcement is a thing that they explicitly say that you should talk about as a community before adopting this.  I think we could either change the wording in this document, or probably better, add another document detailing enforcement policies.

**Comment by reillysiemens** [comment]
After reading some of the [examples](http://contributor-covenant.org/#enforcement) I'm quite enamored with the [Django Code of Conduct Enforcement Manual](https://www.djangoproject.com/conduct/enforcement-manual/) which it looks like jQuery has basically [copied](https://jquery.org/conduct/enforcement-manual/) as well.

**Comment by reillysiemens** [comment]
Personally, I'd be in favor of adopting the Django Enforcement policies with minimal modification.

**Comment by RadicalZephyr** [comment]
Okay, on reading the Django document I have some thoughts.

Broadly speaking I like it. However, there are numerous things that are critical parts of the document that don't apply to Hermit.  These are mostly organization structural differences that reflect the fact that the Django project is vastly larger than Hermit.

These references are to things like Django Software Foundation (DSF), a separate committee for handling CoC violation reports, etc.

If changes those references is what you're referring to @nfrmatk then I'm onboard.  That still leaves a number of things that need to be settled (like what those changes will be ;)

**Comment by reillysiemens** [comment]
That's exactly the kind of thing I'm referring to. The easiest way to proceed might be to have you make what you consider to be logical changes to those sections as the correspond to our organization and I can review those.:D I could also PR your branch with what _I'm_ thinking, but that might be more convoluted I think.

**Comment by RadicalZephyr** [comment]
So, what I'm thinking in regards of the structure of enforcement response, is just to remove mentions of the Django Foundation and the enforcement committee and working group, and intstead refer to the "Hermit Core Team" in all those places.

We could alternatively say the "Bike Barn Core Team" everywhere.  Thoughts?  Most everything else I'll leave in place.

Even if we don't keep bike-barn as a name, we're going to need a non-personal email to put on these documents as the reporting contact.  Maybe just hermit@gmail.com?

**Comment by RadicalZephyr** [comment]
One concern I have with the two documents is that they outline the same process and have much duplicated information.  I think it might be good to remove some of the detail about the enforcement process from the reporting guide to keep it more focused, and just refer to the enforcement guide for more details

**Pull request merged**
